
[tool.pyflow]
name = "pagination_seven"
py_version = "3.9.9"
version = "0.1.0"
authors = ["Brandon Corfman <bcorfman@fastmail.fm>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
pytest = "^7.0.0rc1"

